web3swift.xcodeproj/project.pbxproj
I couldn't compile the library (simulator nor device) as the include was not configured in project.
It's correctly configured in the `podspec` though, so duplicated it to be able to work standalone.
=> Fix import of 'modulemap' for Commoncrypto

web3sTests/Account/EthereumAccountTests.swift, web3sTests/Account/EthereumKeyStorageTests.swift, web3sTests/Client/EthereumClientTests.swift, web3sTests/Contract/ABIDecoderTests.swift, web3sTests/Contract/ABIEncoderTests.swift, web3sTests/ENS/ENSTests.swift, web3sTests/ERC20/ERC20Tests.swift, web3sTests/Extensions/ByteExtensionsTests.swift, web3sTests/Extensions/Data+RandomTests.swift, web3sTests/Extensions/HexExtensionsTests.swift, web3sTests/Extensions/KeccakExtensionsTests.swift, web3sTests/Utils/HexUtilTests.swift, web3sTests/Utils/KeyUtilTests.swift
Just a minor cleanup that I did when reading and running the unit tests
Also the 'account' test failed for me with my private/public key because of case sensitivity
=> Improvement: Use XCTAssertEqual for comparison

web3sTests/Client/EthereumClientTests.swift, web3swift.xcodeproj/project.pbxproj, web3swift/src/Client/EthereumClient.swift, web3swift/src/Client/Models/EthereumBlockInfo.swift
We add simple support for `getBlockByNumber`:
- Always returning transaction hashes
- Only exposing in the block info this data: the number, transaction hashes, timestamp
=> Feature: Support 'getBlockByNumber'

Gemfile.lock, Podfile, Podfile.lock
Changelog:
3.1.0
Swift 4.1 compatibility for Linux and macOS
Fix warnings for Swift 4.1
There were no functional changes.
3.0.2
Fixed product definitions in Package.swift not to create a duplicate library. (Issue #37)
There were no functional changes.
=> [UPDATE] BigInt library

web3sTests/Client/EthereumClientTests.swift, web3sTests/TestConfig.swift, web3swift/src/Client/EthereumClient.swift, web3swift/src/Client/JSONRPC.swift
Temporary change to allow clients of the library to adapt later if '0x' was returned.
We'll add later a proper error enum to notify caller that execution reverted instead.
=> Handle responses as per old geth version

web3swift.xcodeproj/project.pbxproj, web3swift/src/Client/EthereumClient.swift, web3swift/src/Client/RecursiveLogCollector.swift
Infura doesn't support return more than 10k results per query which can be an issue while getting logs as some of the functions, e.g. ERC20's `transferEventsTo`, have the assumption they can get all the logs from the starting block to the end block in a single call. 
To simplify the consumption of the API without breaking its ergonomics there's a new log collector entity underneath that will split the query in multiple as required to aggregate all the logs between the two blocks provided and return them in a single pass to consumers.
This can be reformed in the next major version by making some breaking changes in the public API.
=> [FIX] Return all logs from the starting block to the end block by doing recursive queries when needed

Podfile, Podfile.lock, Pods/BigInt/README.md, Pods/BigInt/Sources/Data Conversion.swift, Pods/BigInt/Sources/Random.swift, Pods/Manifest.lock, Pods/Target Support Files/BigInt/BigInt-Info.plist, web3sTests/Contract/ABIFunctionEncoderTests.swift, web3swift/src/Contract/Statically Typed/ABIFunctionEncoder.swift, web3swift/src/ERC721/ERC721.swift
The API uses 'container' types `BigInt`, `BigUInt` and `Data`, but in Solidity those can have specific size (`Data` is also dynamic unless specifically known size).
If a specific size should be used to encode, a `staticSize` parameter should be passed when using `BigInt`, `BigUInt` or `Data`. Currently that size was ignored for Ints.
=> Add support for custom uint/int types, instead of assuming always 256

web3sTests/Account/EthereumAccount+SignTransactionTests.swift, web3swift/src/Account/EthereumAccount+SignTransaction.swift, web3swift/src/Account/EthereumAccount.swift, web3swift/src/Client/EthereumClient.swift, web3swift/src/Client/Models/EthereumTransaction.swift
In solving my own issue #141 I thought I'd offer my solution as a PR. 
If I have missed any crucial issues with this feel free to let me know and/or ignore.
**Problem**
Obtaining a signed transaction for later submission is not possible as sign(_ transaction: EthereumTransaction) is not publicly available
**Solution**
Make the function publicly available, including dependent private variables
=> Make sign(_ transaction: EthereumTransaction) publicly available

web3.swift.podspec
It is found that in React Native builds, which does not seems to `use_framework!`, the swift compiler is unable to find the `BigInt` and `GenericJSON` dependencies for the `web3.swift` during the build process, causing build failure. After reviewing the project configuration, I have found the `pod_target_xcconfig` in podspec to be supcisious, and the problem was fixed after adding `$(inherited)` to the config.
=> fix: add inhertied to pod_target_xcconfig

web3sTests/ERC721/ERC721Tests.swift, web3swift/src/Client/EthereumClient.swift, web3swift/src/Client/JSONRPC.swift, web3swift/src/ERC721/ERC721.swift
Hi,
Im using your framework and I love it. I tried to use build on Docker swift 5.5 version and I got the following error:
> #14 10.61 /build/.build/checkouts/web3.swift/web3swift/src/Client/EthereumClient.swift:13:35: error: 'URLSessionConfiguration' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
#14 10.61     init(url: URL, sessionConfig: URLSessionConfiguration)
#14 10.61                                   ^~~~~~~~~~~~~~~~~~~~~~~
#14 10.61 Foundation.URLSessionConfiguration:2:18: note: 'URLSessionConfiguration' has been explicitly marked unavailable here
#14 10.61 public typealias URLSessionConfiguration = AnyObject
#14 10.61                  ^
#14 10.61 /build/.build/checkouts/web3.swift/web3swift/src/Client/EthereumClient.swift:50: …
=> Add Linux Swift 5.1 support

web3sTests/Account/EthereumAccountTests.swift, web3swift/src/Account/EthereumAccount.swift
It would be nice to be able to import a wallet account! Fixes #111 
We don't want to edit the package to add that functionality locally
=> Fix import wallet account instead of creating account? #111

README.md, web3sTests/Client/EthereumClientTests.swift, web3sTests/Contract/ABIEventTests.swift, web3sTests/ENS/ENSTests.swift, web3sTests/ERC165/ERC165Tests.swift, web3sTests/ERC20/ERC20Tests.swift, web3sTests/ERC721/ERC721Tests.swift, web3sTests/Multicall/MulticallTests.swift, web3swift/src/Client/EthereumClient.swift, web3swift/src/Client/JSONRPC.swift, web3swift/src/Contract/Statically Typed/EthereumClient+Static.swift, web3swift/src/ENS/ENSMultiResolver.swift, web3swift/src/ENS/EthereumNameService.swift, web3swift/src/ERC165/ERC165.swift, web3swift/src/ERC20/ERC20.swift, web3swift/src/ERC721/ERC721.swift, web3swift/src/Multicall/Multicall.swift
Adds support for async/await. All the async methods call the original closure based methods. 
We must not remove/deprecate closure based methods for backwards compatibility
Fixes: #147
Heavily tested on my Project and work like a charm!
=> Add async APIs for callbacks, add tests for async methods

web3swift/src/Client/Models/EthereumLog.swift
See issue: https://github.com/argentlabs/web3.swift/issues/197
TLDR: it is sometimes missing in `eth_getTransactionReceipt` response.
=> Make removed property of EthereumLog optional

Package.swift, web3sTests/Client/EthereumClientTests.swift, web3sTests/ENS/ENSOffchainTests.swift, web3sTests/ENS/ENSTests.swift, web3sTests/OffchainLookup/OffchainLookupTests.swift, web3swift/src/Client/EthereumClient+Call.swift, web3swift/src/Client/EthereumClient.swift, web3swift/src/Client/JSONRPC.swift, web3swift/src/Contract/Statically Typed/ABIFunction.swift, web3swift/src/Contract/Statically Typed/ABIFunctionEncodable.swift, web3swift/src/Contract/Statically Typed/ABIFunctionEncoder.swift, web3swift/src/Contract/Statically Typed/ABIRevertError.swift, web3swift/src/Contract/Statically Typed/EthereumClient+Static.swift, web3swift/src/ENS/ENSContracts.swift, web3swift/src/ENS/ENSMultiResolver.swift, web3swift/src/ENS/ENSResolver.swift, web3swift/src/ENS/EthereumNameService.swift, web3swift/src/ERC165/ERC165.swift, web3swift/src/ERC20/ERC20.swift, web3swift/src/ERC721/ERC721.swift, web3swift/src/OffchainLookup/OffchainLookup.swift, web3swift/src/Utils/PropertyWrappers.swift
Add support for offchain read in `eth_call`, and more specifically add support for offchain ENS resolution.
An example to resolve is:
`offchainexample.eth` (both in ropsten and mainnet)
See
https://eips.ethereum.org/EIPS/eip-3668
There's another bit of related but not the same work, but will address this here : #205
=> [ADD] Offchain Read support (EIP-3668) for eth_call and ENS resolution

web3sTests/ENS/ENSOffchainTests.swift, web3sTests/ENS/ENSTests.swift, web3swift/src/ENS/ENSResolver.swift, web3swift/src/ENS/EthereumNameService.swift
https://docs.ens.domains/ens-improvement-proposals/ensip-10-wildcard-resolution
#214
=> [ADD] Support wildcard domain resolution (EIP-10)

web3sTests/ENS/ENSOffchainTests.swift, web3swift/src/ENS/ENSResolver.swift, web3swift/src/ENS/EthereumNameService.swift
Resolving ENS without wildcard, **then** ENS with wildcard on same resolver. Also added test for inverse order.
=> [FIX] ENS wildcard resolution caching

web3sTests/Client/EthereumClientTests.swift, web3swift/src/Client/EthereumClient+Call.swift, web3swift/src/Client/EthereumClient.swift, web3swift/src/Client/JSONRPC.swift, web3swift/src/Client/RecursiveLogCollector.swift, web3swift/src/Contract/Statically Typed/EthereumClient+Static.swift, web3swift/src/ENS/EthereumNameService.swift, web3swift/src/ERC165/ERC165.swift, web3swift/src/ERC20/ERC20.swift, web3swift/src/ERC721/ERC721.swift, web3swift/src/Multicall/Multicall.swift
_Its more convenience to use `Result` to reduce the optionals._
Resolves #219 .
That PR will open the road for the WebSocket integration #182 
All the deprecated methods have been putted in extensions with `// MARK: - Deprecated` for easy removal
=>  Make use of Result on completion

web3sTests/Client/EthereumClientTests.swift, web3swift/src/Client/EthereumClient.swift
Good afternoon team, I'm using your library to build an app with web3. Thank you for your work, it has been really helpful. I would like to propose a small improvement.
While building my model I have found that [EthereumClient](https://github.com/argentlabs/web3.swift/blob/master/web3swift/src/Client/EthereumClient.swift) function [eth_estimateGas](https://github.com/argentlabs/web3.swift/blob/master/web3swift/src/Client/EthereumClient.swift#L31) does not use the account parameter and would be good to remove it.
I have a model Token where I inject contract address and `EthereumClient` for the read functions. For the write functions I want the model to return a transaction with `GasPrice` and `GasLimit` calculated. Having the account as a parameter of `eth_estimateGas`, forces me to inject …
=> Remove unused account in eth_estimateGas

web3swift/src/Client/EthereumClient.swift
Currently the queue priorities are set to `.background`, and this is a problem when web3 methods are called from high priority tasks (eg in the Argent app). In Xcode 14 you get thread performance checker warnings about potential priority inversions, which is what happens when a high priority task is waiting on a low priority (.background) task, it effectively demotes the high priority task to low priority.
Here you see a high priority task in Argent being held up waiting on the low priority (background) task in web3:
By removing the explicit QoS / Priority the OS decides what priority to give the tasks. This gets rid of the warnings in Xcode and you no longer get these priority inversions.
=> [FIX] Remove explicit queue priorities

Package.swift, web3sTests/Account/EthereumAccount+SignTypedTests.swift, web3sTests/Account/ethermail_signTypedDataV4.json, web3sTests/Account/real_word_opensea_signTypedDataV4.json, web3swift/src/Account/TypedData.swift
Context: https://github.com/argentlabs/web3.swift/issues/277
Adding support of custom typed array in `signableHash`. Cross verified new unit test cases with [@metamask/eth-sig-util](https://github.com/MetaMask/eth-sig-util).
**Tests:**
1. All unit tests in `EthereumAccount_SignTypedTests`
=> Support Custom Typed Array

README.md, web3sTests/Account/EthereumAccountTests.swift, web3sTests/Account/EthereumKeyStorageTests.swift, web3sTests/Mocks/TestEthereumKeyStorage.swift, web3swift/src/Account/EthereumAccount.swift, web3swift/src/Account/EthereumKeyStorage+Password.swift, web3swift/src/Account/EthereumKeyStorage.swift
To avoid conflicts and be more explicit #263
=> Refactor Account create/import APIs

web3sTests/Client/EthereumClientTests.swift, web3swift/src/Client/EthereumClientProtocol.swift, web3swift/src/Client/EthereumWebSocketClient.swift, web3swift/src/Client/Models/EthereumSubscription.swift, web3swift/src/Client/NetworkProviders/WebSocketNetworkProvider.swift
Added the missing WebSocket Client `logs` subscription.
=> [ADD] missing logs subscription

web3sTests/Multicall/MulticallTests.swift, web3swift/src/Multicall/Multicall.swift, web3swift/src/Multicall/MulticallContract.swift
The multicall v2 supported contracts can be found [here](https://github.com/makerdao/multicall)
=> [ADD] Support multicall v2

web3sTests/Account/EthereumAccountTests.swift, web3sTests/Client/EthereumClientTests.swift, web3sTests/ENS/ENSTests.swift, web3sTests/OffchainLookup/OffchainLookupTests.swift, web3sTests/Utils/KeyUtilTests.swift, web3swift/src/Account/EthereumAccount.swift, web3swift/src/Account/EthereumKeyStorage.swift, web3swift/src/Client/BaseEthereumClient.swift, web3swift/src/Client/EthereumClient+Call.swift, web3swift/src/Client/Models/EthereumAddress.swift, web3swift/src/Client/Models/EthereumTransaction.swift, web3swift/src/Contract/Statically Typed/ABIDecoder+Static.swift, web3swift/src/Contract/Statically Typed/ABIEncoder+Static.swift, web3swift/src/ENS/ENSContracts.swift, web3swift/src/Utils/RLP.swift
This will avoid any string comparison issues. Also the string value
shouldn't be exposed so explicity, created different converison methods
in the type.
=> [CHANGE] EthereumAddress: Deprecate `value`. Compare by converting to number

.github/workflows/CI.yml, web3sTests/Client/EthereumClientTests.swift, web3sTests/ENS/ENSOffchainTests.swift, web3sTests/ENS/ENSTests.swift, web3sTests/ERC165/ERC165Tests.swift, web3sTests/TestConfig.swift, web3sTests/ZKSync/EthereumClient+ZKSyncTests.swift, web3swift/src/ERC165/ERC165.swift, web3swift/src/Multicall/Multicall.swift, web3swift/src/ZKSync/ABIFunction+ZKSync.swift
Fixes https://github.com/argentlabs/web3.swift/issues/297
=> Fix ENS reverse ENS resolution when supportsInterface is not implemented in contract

web3sTests/Client/EthereumClientTests.swift, web3sTests/Contract/ABIEventTests.swift, web3sTests/ENS/ENSOffchainTests.swift, web3sTests/ENS/ENSTests.swift, web3sTests/ERC1271/ERC1271Tests.swift, web3sTests/ERC165/ERC165Tests.swift, web3sTests/ERC20/ERC20Tests.swift, web3sTests/ERC721/ERC721Tests.swift, web3sTests/Multicall/MulticallTests.swift, web3sTests/OffchainLookup/OffchainLookupTests.swift, web3sTests/SIWE/SIWETests.swift, web3sTests/SIWE/SiweVerifierTests.swift, web3sTests/TestConfig.swift, web3sTests/ZKSync/EthereumClient+ZKSyncTests.swift, web3swift/src/Client/BaseEthereumClient.swift, web3swift/src/Client/HTTP/EthereumHttpClient.swift, web3swift/src/Client/Protocols/EthereumClientProtocol.swift, web3swift/src/Client/Protocols/EthereumProvider.swift, web3swift/src/Client/WSS/EthereumWebSocketClient.swift, web3swift/src/ENS/ENSMultiResolver.swift, web3swift/src/ENS/EthereumNameService.swift, web3swift/src/Multicall/Multicall.swift, web3swift/src/SIWE/SiweVerifier.swift, web3swift/src/ZKSync/ZKSyncProvider.swift
Using semaphores across Structured Concurrency Tasks is not safe, so need to remove it here
=> [FIX] Remove potential deadlock when using async-await. Provide network at client initialization instead
