- web3swift/src/Client/Models/EthereumAddress.swift
- web3swift/src/Client/Models/EthereumLog.swift
- web3swift/src/Client/Models/EthereumTransactionReceipt.swift
+ better custom Codable conformity + Hashable
> EthereumAddress instead of String

- web3swift/src/ERC721/ERC721.swift
Even if not specified in standard, there's some contracts providing
those keys at root, so it's better if library retrieves those instead of
failing.
> [IMPROVE] Try to match 'title', 'description', and 'image' from the JSON root

- web3swift/src/Client/EthereumClient.swift
> [ADD] eth_estimateGas support

- web3swift/src/Client/EthereumClient.swift
- web3swift/src/Client/JSONRPC.swift
Notify upstream if the query fails with too many results.
> Check for "Too Many Results" error

- web3sTests/Client/EthereumClientTests.swift
- web3swift/src/Client/EthereumClient.swift
- web3swift/src/Client/JSONRPC.swift
Errors spec (moving target, but still useful):
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md:
https://eth.wiki/json-rpc/json-rpc-error-codes-improvement-proposal
> [TIDY] Include 'execution error', and also rename error as per spec

- web3sTests/Account/EthereumAccountTests.swift
- web3sTests/Client/EthereumClientTests.swift
- web3sTests/Utils/KeyUtilTests.swift
- web3swift/src/Account/EthereumAccount.swift
- web3swift/src/Client/EthereumClient.swift
- web3swift/src/Client/RecursiveLogCollector.swift
- web3swift/src/Contract/Statically Typed/EthereumClient+Static.swift
- web3swift/src/Utils/KeyUtil.swift
- web3swift/src/Utils/KeystoreUtil.swift
> [CHANGE] Use 'EthereumAddress' in APIs instead of 'String'

- README.md
Hello! While I was going through your readme I thought I could slightly improve readability by adding language params to the code snippets. Please let me know if you'd like me to change something in the PR (e.g. param for solidity - I chose javascript but maybe there's a better one that shares more syntax).
> Improve readability of snippets in README.md

- web3sTests/Utils/KeyUtilTests.swift
- web3swift/src/Utils/KeyUtil.swift
- add `KeyUtil.recoverPublicKey` implementation with corresponding test
> add KeyUtil.recoverPublicKey

- web3swift/src/Account/EthereumAccount+SignTransaction.swift
- web3swift/src/Account/EthereumAccount.swift
- web3swift/src/Client/EthereumClient.swift
- web3swift/src/Client/Models/EthereumTransaction.swift
- web3swift/src/Contract/Statically Typed/EthereumClient+Static.swift
* Made EthereumAccountProtocol public
* Made SignedTransaction init public
This will allow an app to implement its own EthereumAccount
> Allow to use custom Ethereum Account implementation

- web3.swift.podspec
- web3swift/src/Utils/KeyDerivation.swift
Also updated CI to lint the library
> [TIDY] Compatibility with embedded CryptoSwift, when importing with Cocoapods

- web3swift/src/Utils/KeyUtil.swift
This PR fixes a weird issue around signing/hashing on Linux, check the issue for more details.
Closes #175
> Fixing weird issue around signing/hashing on Linux

- web3sTests/Account/EthereumKeyStorageTests.swift
- web3swift/src/Account/EthereumAccount.swift
- web3swift/src/Account/EthereumKeyStorage+Password.swift
> Add private key encryption/decryption functionality to EthereumKeyStorageProtocol extension

- web3swift/src/ENS/EthereumNameService.swift
Just missing the public for the async variants
> Making Ethereum async await apis public

- web3sTests/Client/EthereumClientTests.swift
- web3sTests/ERC20/ERC20Tests.swift
- web3sTests/TestConfig.swift
- web3swift/src/Client/EthereumClient.swift
- web3swift/src/Client/JSONRPC.swift
- web3swift/src/Contract/Statically Typed/EthereumClient+Static.swift
- web3swift/src/ENS/EthereumNameService.swift
- web3swift/src/ERC20/ERC20.swift
- web3swift/src/ERC721/ERC721.swift
Fixes #120 
Also addressing the changes suggested in #183 @dnKaratzas
> [CHANGE] Remove workaround returning '0x' when eth_call fails

- web3swift/src/ENS/EthereumNameService.swift
to avoid repeating 'supportsInterface' calls
#210
> [ADD] ENS resolvers: Cache resolvers by address 

- Package.resolved
- Package.swift
Change secp256k1 package to a[ maintained package.](https://github.com/GigaBitcoin/secp256k1.swift)
Original `secp256k1` will throw error like below
> fix: secp256k1 error

- web3swift/src/Contract/Statically Typed/EthereumClient+Static.swift
> Fix event properties inaccessible

- Package.resolved
- web3swift/src/Client/EthereumHttpClient.swift
- web3swift/src/Client/EthereumWebSocketClient.swift
The same change as was made in https://github.com/argentlabs/web3.swift/pull/273.
Could not cherry pick as code has been refactored since that branch.
> "Cherry pick" queue priorities fix from #273

- Package.resolved
- Package.swift
> [UPDATE] GenericJSON dependency version

- Package.swift
> [FIX] Support watchOS

- web3.swift.podspec
- web3swift/src/Client/EthereumClientProtocol.swift
- web3swift/src/Client/EthereumWebSocketClient.swift
- web3swift/src/Client/NetworkProviders/EventLoopGroupProvider.swift
- web3swift/src/Client/NetworkProviders/NetworkProviderProtocol.swift
- web3swift/src/Client/NetworkProviders/WebSocketConfiguration.swift
- web3swift/src/Client/NetworkProviders/WebSocketNetworkProvider.swift
> [FIX] Building with Cocoapods (no NIO/websocket feature)

- README.md
replacing `EthereumClient` with `EthereumHttpClient`
> Minor correction in Readme

- .github/workflows/CI.yml
- .gitignore
- README.md
- scripts/setupKey.sh
- web3sTests/TestConfig.swift
> [CHANGE] Remove test key from repository

- web3swift/src/ERC165/ERC165.swift
> [FIX] ENS resolution (ported fix from develop)
